PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?beverage WHERE {
  ?beverage rdf:subClassOf dbo:Non-alcoholic_drink .
} LIMIT 100
