PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbc: <http://dbpedia.org/resource/Category/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?beverage_id ?description ?y WHERE {
  ?beverage_id dct:subject dbc:Non-alcoholic_drinks .
  ?beverage_id rdfs:comment ?description .
} LIMIT 100
