PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
SELECT ?name
WHERE {

    ?location rdf:type dbo:Country ;
              dbp:populationCensus ?pop ;
              rdfs:label ?name .
}
GROUP BY ?name
ORDER BY DESC (?pop)
